### PR TITLE
Fixes to the Error.vue component and popup mode

### LINKED ISSUE #89: Error component issues
Hi,

The error component uses `{{msg}}` but `msg()` is declared as a method. I believe it should be a computed value, like `show`

### PR DESCRIPTION
**Pull request by stevehobbsdev**
This PR fixes #89 and the `Error.vue` component, where the `msg` method is now a computed property, and the `show` prop is removed altogether.

It also takes care to make sure that the `error` prop is set correctly when using the SDK in popup mode for authentication. As part of investigating that, I discovered that the `user` and `isAuthenticated` props were not being set correctly when using popup mode, which has now been rectified in this PR.

### CODE REVIEW

File: 01-Login/src/auth/authWrapper.js [hunk 1]
```diff
@@ -32,21 +32,23 @@ export const useAuth0 = ({
 
         try {
           await this.auth0Client.loginWithPopup(o);
+          this.user = await this.auth0Client.getUser();
+          this.isAuthenticated = await this.auth0Client.isAuthenticated();
```
Comment (joshcanhelp) [inline 01-Login/src/auth/authWrapper.js]: Is this something that might get updated while the app is still in memory? Wondering if this should be the `auth0Client.isAuthenticated` method itself rather than the current value ...

Comment (stevehobbsdev) [reply 01-Login/src/auth/authWrapper.js]: Don't worry, it will be. `isAuthenticated` is a reactive Vue property, so if the state of authentication ever changes, we can just set this value and everything that is watching it will update (Vue components, anything using `$watch`, etc). We just make sure that its value is set whenever we check the authentication state inside the wrapper.
